In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
model_values = pd.read_csv('inference_full_results_00.csv',delimiter=';')

In [5]:
model_values.head(20)

,timestamp_train,predicted_delay_train,true_delay_train,timestamp_validation,predicted_delay_validation,true_delay_validation,timestamp_test,predicted_delay_test,true_delay_test
0,2017-06-08 14:30:00,8.216854,14.734661,2017-10-28 18:00:00,12.542548,10.201201,2017-12-18 16:00:00,12.728409,9.364846
1,2017-06-08 15:00:00,8.739904,17.297508,2017-10-28 18:30:00,12.244441,11.620202,2017-12-18 16:30:00,13.022123,12.482188
2,2017-06-08 15:30:00,8.983679,13.815071,2017-10-28 19:00:00,11.950871,12.910000,2017-12-18 17:00:00,13.427076,11.702821
3,2017-06-08 16:00:00,9.271424,14.993851,2017-10-28 19:30:00,11.697115,13.101298,2017-12-18 17:30:00,13.496639,15.763704
4,2017-06-08 16:30:00,9.480982,16.984011,2017-10-28 20:00:00,11.282078,12.773593,2017-12-18 18:00:00,13.445535,17.643137
5,2017-06-08 17:00:00,9.998398,12.849744,2017-10-28 20:30:00,10.967566,9.588889,2017-12-18 18:30:00,13.296183,16.670752
6,2017-06-08 17:30:00,10.312218,19.245134,2017-10-28 21:00:00,10.553034,10.059167,2017-12-18 19:00:00,13.139711,15.253780
7,2017-06-08 18:00:00,10.491616,15.424767,2017-10-28 21:30:00,10.238052,9.341892,2017-12-18 19:30:00,13.073726,12.487879
8,2017-06-08 18:30:00,10.585863,12.729580,2017-10-28 22:00:00,9.761759,1.904902,2017-12-18 20:00:00,12.882596,15.504167
9,2017-06-08 19:00:00,10.582047,12.773835,2017-10-28 22:30:00,9.502166,5.346552,2017-12-18 20:30:00,12.794250,11.897223
10,2017-06-08 19:30:00,10.620492,11.795122,2017-10-28 23:00:00,8.973534,7.065432,2017-12-18 21:00:00,12.531452,11.465812
11,2017-06-08 20:00:00,10.432104,10.326256,2017-10-28 23:30:00,8.558372,4.730556,2017-12-18 21:30:00,12.353591,6.027350
12,2017-06-08 20:30:00,10.235504,9.446175,2017-10-29 00:00:00,8.356851,8.356667,2017-12-18 22:00:00,12.021548,8.839047
13,2017-06-08 21:00:00,9.977600,7.959848,2017-10-29 00:30:00,7.889903,5.816667,2017-12-18 22:30:00,11.865550,7.905128
14,2017-06-08 21:30:00,9.658012,8.213636,2017-10-29 01:00:00,7.346906,0.054167,2017-12-18 23:00:00,11.386909,12.015789
15,2017-06-08 22:00:00,9.250131,5.586036,2017-10-29 01:30:00,6.882666,2.305556,2017-12-18 23:30:00,11.090835,9.054167
16,2017-06-08 22:30:00,8.892831,7.584409,2017-10-29 02:00:00,6.381631,2.938889,2017-12-19 00:00:00,11.660707,81.763161
17,2017-06-08 23:00:00,8.320103,6.592593,2017-10-29 02:30:00,5.844579,2.658333,2017-12-19 00:30:00,10.914192,6.680702
18,2017-06-08 23:30:00,8.023953,8.603623,2017-10-29 03:00:00,5.313339,4.068182,2017-12-19 01:00:00,10.335969,1.316667
19,2017-06-09 00:00:00,7.628175,5.551111,2017-10-29 03:30:00,4.861176,3.951852,2017-12-19 01:30:00,9.869041,1.922917

In [7]:
# Train dataframe: keep only train columns
train_df = model_values.drop(
    columns=["timestamp_validation","predicted_delay_validation", "true_delay_validation", "timestamp_test","predicted_delay_test", "true_delay_test"]
).dropna()

# Validation dataframe: keep only validation columns
val_df = model_values.drop(
    columns=["timestamp_train","predicted_delay_train", "true_delay_train", "timestamp_test","predicted_delay_test", "true_delay_test"]
).dropna()

# Test dataframe: keep only test columns
test_df = model_values.drop(
    columns=["timestamp_train","predicted_delay_train", "true_delay_train", "timestamp_validation","predicted_delay_validation", "true_delay_validation"]
).dropna()

In [8]:
train_df.shape

(3032, 3)

In [12]:
train_df = train_df.copy()
train_df["residuals"] = train_df["true_delay_train"] - train_df["predicted_delay_train"]

val_df = val_df.copy()
val_df["residuals"] = val_df["true_delay_validation"] - val_df["predicted_delay_validation"]

test_df = test_df.copy()
test_df["residuals"] = test_df["true_delay_test"] - test_df["predicted_delay_test"]

In [13]:
train_df.head()

       timestamp_train  predicted_delay_train  true_delay_train  residuals
0  2017-06-08 14:30:00               8.216854         14.734661   6.517807
1  2017-06-08 15:00:00               8.739904         17.297508   8.557604
2  2017-06-08 15:30:00               8.983679         13.815071   4.831392
3  2017-06-08 16:00:00               9.271424         14.993851   5.722426
4  2017-06-08 16:30:00               9.480982         16.984011   7.503029

In [16]:
train_df = train_df.rename(columns={
    "timestamp_train": "timestamp",
    "true_delay_train": "ytrue",
    "predicted_delay_train": "ypred"
})

val_df = val_df.rename(columns={
    "timestamp_validation": "timestamp",
    "true_delay_validation": "ytrue",
    "predicted_delay_validation": "ypred"
})

test_df = test_df.rename(columns={
    "timestamp_test": "timestamp",
    "true_delay_test": "ytrue",
    "predicted_delay_test": "ypred"
})

In [17]:
train_df.head()

             timestamp     ypred      ytrue  residuals
0  2017-06-08 14:30:00  8.216854  14.734661   6.517807
1  2017-06-08 15:00:00  8.739904  17.297508   8.557604
2  2017-06-08 15:30:00  8.983679  13.815071   4.831392
3  2017-06-08 16:00:00  9.271424  14.993851   5.722426
4  2017-06-08 16:30:00  9.480982  16.984011   7.503029

In [18]:
train_df.to_csv("lstm_train_predictions.csv")
val_df.to_csv("lstm_val_predictions.csv")
test_df.to_csv("lstm_test_predictions.csv")

print("Saved successfully!")

Saved successfully!

In [89]:
features_df = pd.read_csv('final_dataset_corrected.csv',delimiter=';')

In [90]:
features_df.columns.tolist()

['Unnamed: 0',
 'timestamp',
 'FLATBUSH AV/PROSPECT PARK ENT',
 'LIVINGSTON ST/NEVINS ST',
 'FLATBUSH AV/BERGEN ST',
 'CADMAN PLZ W/MONTAGUE ST',
 'FLATBUSH AV/PLAZA ST E',
 'avg_delay',
 'temperature_c',
 'precipitation',
 'windspeed_kmh',
 'month',
 'week_day',
 'hour',
 'is_weekend',
 'is_holiday',
 'dayly_lag',
 'weekly_lag']